### ISSUE TITLE
Standardization of dummy variables

### ISSUE THREAD

**Issue by aaronliang07** [isdsucph/isds2024#8]
I'm wondering what the common practice is regarding the standardization of dummy variables. Should we include them in the standardization just as we do with continuous variables, or leave them as 0 or 1 values? Will this affect model performance? I looked online and it while I couldn't find a consensus answer it seems that most are leaning to not standardizing, while I remember in our exercises we did have some dummy variables which we standardized.

**Comment by abjer** [comment]
Good question! In general we re-scale to gain performance in ML models, specifically thus based on linear models. The reason is that they try to try trade off different variables and underlying this is an assumption that the variables are scaled. The downside is that it means that we cannot interpret our variables in the same way (in particular binary) thus we only rescale our machine but not standard statistical models.
